spring.application.name=payment-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/payment_processing_system_kafka_project
spring.datasource.username=root
spring.datasource.password=nabeel007dar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=payment-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Customer 102 deliberately produces failed payment
payment.demo.failure-customer-id=102

# For scaling, run second instance with worker-id=2
event.worker-id=1